### ISSUE TITLE
What's about ESP32 support ?

### ISSUE THREAD

**Issue by Vorms** [jgromes/KiteShield#1]
All is in the title...

Best regards

**Comment by jgromes** [comment]
RadioShield is compatible with any board that's compatible with Arduino Uno R3.

Did you mean to post this in https://github.com/jgromes/RadioLib?

**Comment by Vorms** [comment]
yes of corse for the library 
Thanks
I am intersted about a RF69 -> MQTT !

Best regards and thanks for your works

**Comment by jgromes** [comment]
Could you post this to the library repository? Thanks
